version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: observations-postgres
    environment:
      POSTGRES_DB: observations_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d observations_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
